version: "2"
services:
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
        volumes:
            - ./:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
    php-ssl:
        build:
            context: .
            dockerfile: PHPDockerfile
        ports:
            - 8081:80
            - 8443:443
        volumes:
            - ./:/var/www/html
            - ${APACHE_LOG_VOLUME}:/var/log/apache2
        environment:
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD : ${DB_PASSWORD}
            DB_NAME : ${DB_NAME}
            DB_HOSTNAME : 'db'
volumes:
    persistent: